### ISSUE TITLE
problem in install.sh

### ISSUE THREAD

**Issue by jinnu92** [capt-meelo/LazyRecon#5]
root@kali:~/tools/webapplication/LazyRecon# bash install.sh 
install.sh: line 69: syntax error near unexpected token `newline'
install.sh: line 69: `        ~/go/bin/subfinder --set-config VirustotalAPIKey=<APU-KEY-HERE>'

needed to remove <> from the main script

**Comment by capt-meelo** [comment]
You have to change the string `<API-KEY-HERE>` (including **<** and **>**) with your API keys.
